#!/usr/bin/env python3
"""
build_web_ui.py
----------------
Generates web_ui.h -- a PROGMEM C header containing the ESP32's on-device web
control panel (HTML/CSS/JS, all inline, one file) and a static HTML rendering
of PROTOCOL.md for the on-device "Docs" tab. Same pattern as
coolledx_fallback.h (Python generates it, arduino-cli compiles it straight
into flash) -- no SD card dependency, no new upload mechanism, works even on
a board with no SD card wired up at all.

Why PROTOCOL.md gets converted to static HTML here rather than shipped as
raw markdown + a JS renderer: the ESP32's WiFi AP has no internet access, so
any markdown-parser library normally loaded from a CDN wouldn't load. This
avoids that entirely -- Python renders it once at bake time, plain HTML ships
in flash, zero JS dependencies. Images referenced in PROTOCOL.md are dropped
(a caption note is substituted) since embedding the actual JPEGs would add
close to a megabyte to flash -- see docs_images/ or the repo's PROTOCOL.md
directly for the photos.

Raw-send examples (for the Raw Send playground tab) are generated by calling
the real, hardware-verified *_bytes()/*_command_bytes() functions in
bake_messages_coolledux.py directly -- never hand-copied hex -- so the
examples can't drift out of sync with the actual protocol implementation.

Run this after bake_messages_coolledux.py (or anytime PROTOCOL.md or the
example set changes) and copy the resulting web_ui.h into the sketch folder,
same as coolledx_fallback.h.
"""

import html
import re
import base64

import bake_messages_coolledux as bmc

PROTOCOL_MD_PATH = "PROTOCOL.md"
OUTPUT_HEADER = "web_ui.h"


# ---------------------------------------------------------------------------
# Minimal markdown -> HTML converter. No external dependencies (keeps this
# script's own REQUIRES as small as bake_messages_coolledux.py's), and only
# needs to handle the subset of markdown PROTOCOL.md actually uses: headers,
# fenced code blocks, tables, bold/inline-code/links, hr, images (dropped),
# and a couple of raw embedded HTML blocks (passed through as-is).
# ---------------------------------------------------------------------------

def _inline(text: str) -> str:
    text = html.escape(text, quote=False)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", r"<p><i>[photo: \1]</i></p>", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    return text


def markdown_to_html(md: str) -> str:
    lines = md.split("\n")
    out = []
    i = 0
    in_code = False
    code_lines = []
    in_table = False
    table_rows = []
    paragraph = []
    in_list = False

    def flush_paragraph():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False
        if paragraph:
            out.append("<p>" + _inline(" ".join(paragraph)) + "</p>")
            paragraph.clear()

    def flush_table():
        nonlocal in_table
        if table_rows:
            out.append("<table class=\"md-table\">")
            header, *rest = table_rows
            out.append("<tr>" + "".join(f"<th>{_inline(c)}</th>" for c in header) + "</tr>")
            for row in rest:
                out.append("<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in row) + "</tr>")
            out.append("</table>")
        table_rows.clear()
        in_table = False

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if stripped.startswith("```"):
            if not in_code:
                flush_paragraph()
                in_code = True
                code_lines = []
            else:
                out.append("<pre><code>" + html.escape("\n".join(code_lines)) + "</code></pre>")
                in_code = False
            i += 1
            continue
        if in_code:
            code_lines.append(line)
            i += 1
            continue

        if stripped.startswith("<"):
            # Raw embedded HTML block (the color-cycle side-by-side <table>) --
            # drop <img> tags (no image data in flash), pass the rest through.
            flush_paragraph()
            if "<img" in stripped:
                i += 1
                continue
            out.append(line)
            i += 1
            continue

        if stripped.startswith("|"):
            flush_paragraph()
            in_table = True
            if set(stripped.replace("|", "").strip()) <= set("-: "):
                i += 1
                continue
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            table_rows.append(cells)
            i += 1
            continue
        elif in_table:
            flush_table()

        if stripped == "---":
            flush_paragraph()
            out.append("<hr>")
            i += 1
            continue

        m = re.match(r"^(#{1,4})\s+(.*)$", stripped)
        if m:
            flush_paragraph()
            level = len(m.group(1))
            out.append(f"<h{level}>{_inline(m.group(2))}</h{level}>")
            i += 1
            continue

        if stripped == "":
            flush_paragraph()
            i += 1
            continue

        m = re.match(r"^-\s+(.*)$", stripped)
        if m:
            if paragraph:
                flush_paragraph()
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{_inline(m.group(1))}")
            i += 1
            continue

        if in_list:
            # Soft-wrapped continuation line of the current bullet (markdown
            # source wraps at ~80 cols without a blank line between); append
            # to the open <li> rather than starting a new paragraph.
            out[-1] = out[-1] + " " + _inline(stripped)
            i += 1
            continue

        paragraph.append(stripped)
        i += 1

    flush_paragraph()
    flush_table()
    return "\n".join(out)


def render_docs_html() -> str:
    md = open(PROTOCOL_MD_PATH, encoding="utf-8").read()
    body = markdown_to_html(md)
    return f"""<div class="docs">
<p class="docs-note"><i>Rendered from PROTOCOL.md at bake time. Photos are
dropped here (flash-only page) -- see the repo's docs_images/ folder or
PROTOCOL.md directly for those.</i></p>
{body}
</div>"""


# ---------------------------------------------------------------------------
# Raw-send examples for the playground tab. Every entry calls a REAL verified
# function from bake_messages_coolledux.py -- never hand-typed hex -- so
# these can't drift from the actual protocol implementation. Multi-packet
# examples (frame_border_bytes() etc.) are joined with "\n" so the firmware
# can loop through them with the same pacing as any other multi-chunk send.
# ---------------------------------------------------------------------------

def _pkts(packets) -> str:
    if isinstance(packets, (bytes, bytearray)):
        packets = [packets]
    return "\n".join(p.hex() for p in packets)


def build_examples():
    examples = [
        ("Power", "Power ON", bmc.power_command_bytes(True), "CONFIRMED"),
        ("Power", "Power OFF", bmc.power_command_bytes(False), "CONFIRMED"),
        ("Brightness", "Brightness 25%", bmc.brightness_command_bytes(64), "CONFIRMED"),
        ("Brightness", "Brightness 50%", bmc.brightness_command_bytes(128), "CONFIRMED"),
        ("Brightness", "Brightness 100%", bmc.brightness_command_bytes(255), "CONFIRMED"),
        ("Display", "Mirror ON", bmc.mirror_command_bytes(True), "CONFIRMED"),
        ("Display", "Mirror OFF", bmc.mirror_command_bytes(False), "CONFIRMED"),
        ("Display", "Rotate value 2 (distorted -- confirmed real, not mirror)", bmc.rotate_command_bytes(2), "CONFIRMED"),
        ("Light", "Solid Red", bmc.light_color_bytes("#FF0000"), "CONFIRMED"),
        ("Light", "Solid Green", bmc.light_color_bytes("#00FF00"), "CONFIRMED"),
        ("Light", "Solid Blue", bmc.light_color_bytes("#0000FF"), "CONFIRMED"),
        ("Light", "Solid White", bmc.light_color_bytes("#FFFFFF"), "CONFIRMED"),
        ("Light", "Animated color-cycle gradient", bmc.light_color_mode_bytes(), "CONFIRMED"),
        ("Decorative", "Rainbow border (Frame, whole panel)", _pkts(bmc.frame_border_bytes()), "CONFIRMED"),
        ("Queries", "Device info query", bmc.device_info_query_bytes(), "CONFIRMED"),
        ("Queries", "Timer switch query", bmc.timer_switch_query_bytes(), "CONFIRMED"),
        ("Queries", "Countdown query", bmc.countdown_query_bytes(), "CONFIRMED"),
        ("Queries", "Stopwatch query", bmc.stopwatch_query_bytes(), "CONFIRMED"),
        ("Queries", "Scoreboard query", bmc.scoreboard_query_bytes(), "CONFIRMED"),
        ("Settings", "Synchronize time (now)", bmc.synchronize_time_command_bytes(), "CONFIRMED"),
        ("Settings", "Clear timer switch schedule", bmc.timer_switch_set_bytes([]), "CONFIRMED"),
        ("Password", "Password check (dummy '0000' -- read-only, safe)", bmc.password_check_bytes("0000"), "CONFIRMED"),
    ]
    out = []
    for category, label, payload, status in examples:
        hexval = payload if isinstance(payload, str) else _pkts(payload)
        out.append({"category": category, "label": label, "hex": hexval, "status": status})
    return out


# ---------------------------------------------------------------------------
# Preview thumbnails for the Send-to-Display buttons -- like the official
# app's saved-program list, which shows a small preview of each button's
# actual content instead of just a text label. Rendered as inline SVG (no
# image library dependency, crisp at any size, tiny) directly from the same
# glyph-column data the real message is built from, so the preview can never
# drift out of sync with what actually gets sent -- it's the same source data,
# just rendered as a small dot-matrix picture instead of protocol bytes.
# ---------------------------------------------------------------------------

def _svg_pixel_grid(get_pixel_hex, width, height, cell=4):
    """Small SVG: black background, one small circle per lit pixel in its
    actual color -- a miniature mock-up of what the real 64x16 LED matrix
    would show. `cell` controls the SVG's internal coordinate scale, not
    display size (CSS controls the actual on-page size)."""
    svg_w, svg_h = width * cell, height * cell
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {svg_w} {svg_h}">',
             f'<rect width="{svg_w}" height="{svg_h}" fill="#000"/>']
    r = cell * 0.42
    for x in range(width):
        for y in range(height):
            hexc = get_pixel_hex(x, y)
            if hexc:
                cx, cy = x * cell + cell / 2, y * cell + cell / 2
                parts.append(f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r:.1f}" fill="{hexc}"/>')
    parts.append("</svg>")
    return "".join(parts)


def _svg_data_uri(svg: str) -> str:
    b64 = base64.b64encode(svg.encode("utf-8")).decode("ascii")
    return f"data:image/svg+xml;base64,{b64}"


def _text_preview_pixel_fn(text, hex_color, small_font=False):
    columns = bmc.build_small_glyph_columns(text) if small_font else bmc.build_glyph_columns(text)

    def get_pixel(x, y):
        if x >= len(columns):
            return None
        bit = (columns[x] >> (15 - y)) & 1 if y < 16 else 0
        return hex_color if bit else None

    return get_pixel, len(columns)


def build_previews():
    """Returns {code: data-uri} for every real message/animation/game this
    script knows how to render a preview for. Codes with no preview here
    (e.g. a future SD-only custom message never seen by this script) just
    show no thumbnail in the web UI -- graceful, not an error."""
    previews = {}

    for code_name, text, color in bmc.MESSAGES:
        get_pixel, width = _text_preview_pixel_fn(text, color)
        width = max(width, 1)  # BLANK is 0-width text -- still show a tiny black square
        svg = _svg_pixel_grid(get_pixel, width, bmc.SIGN_HEIGHT)
        previews[code_name] = _svg_data_uri(svg)

    # Icon+scrolling-text messages (e.g. LPLATE): preview the icon plus the
    # first stretch of text (as if mid-scroll, arrived at the icon's edge) --
    # same real icon_pixel_fn used by the actual message, so it can't drift.
    for code_name, icon_pixel_fn, icon_width, text, text_color, _step, _delay, small_font in bmc.ICON_SCROLL_MESSAGES:
        text_get_pixel, _text_w = _text_preview_pixel_fn(text, text_color, small_font=small_font)

        def get_pixel(x, y, icon_pixel_fn=icon_pixel_fn, icon_width=icon_width, text_get_pixel=text_get_pixel):
            if x < icon_width:
                return icon_pixel_fn(x, y)
            return text_get_pixel(x - icon_width, y)

        svg = _svg_pixel_grid(get_pixel, bmc.SIGN_WIDTH, bmc.SIGN_HEIGHT)
        previews[code_name] = _svg_data_uri(svg)

    for code_name, text, color, *_rest in bmc.ANIMATIONS:
        # Preview the "arrived" (flush-left) frame -- representative of what
        # the message settles into and holds, not the fly-in motion itself.
        get_pixel, width = _text_preview_pixel_fn(text, color)
        svg = _svg_pixel_grid(get_pixel, width, bmc.SIGN_HEIGHT)
        previews[code_name] = _svg_data_uri(svg)

    # L-plate seamless messages (e.g. THANKS/SORRY): preview the held
    # "message" state (centered text, same real render_message_frame() the
    # actual animation uses), not the idle L-plate -- the text is what
    # distinguishes one button from another at a glance. Scrolling ones
    # (e.g. HONK) are too wide to render_message_frame() statically (that's
    # the whole reason they scroll) -- preview the first SIGN_WIDTH columns
    # of the real text instead, same idea as a scrolling ICON_SCROLL preview.
    for code_name, text, text_color, small_font, scroll, _style in bmc.L_PLATE_SEAMLESS_MESSAGES:
        if scroll:
            msg_pixel_fn, _w = _text_preview_pixel_fn(text, text_color, small_font=small_font)
        else:
            msg_pixel_fn = bmc.render_message_frame(text, text_color, small_font=small_font)
        svg = _svg_pixel_grid(msg_pixel_fn, bmc.SIGN_WIDTH, bmc.SIGN_HEIGHT)
        previews[code_name] = _svg_data_uri(svg)

    # HI: built as a one-off (waving hand, not in L_PLATE_SEAMLESS_MESSAGES) --
    # preview the neutral (tilt=0) wave frame, the real hold content.
    previews["HI"] = _svg_data_uri(_svg_pixel_grid(
        bmc.render_hi_wave_frame_fn(0), bmc.SIGN_WIDTH, bmc.SIGN_HEIGHT))

    # SNAKE: not literally frame-accurate (that's baked pixel data, not text/
    # glyph-derived like everything else here) -- a small hand-drawn
    # green-snake-and-red-apple icon instead, purely symbolic.
    def snake_icon(x, y):
        body = {(1, 8), (2, 8), (3, 8), (4, 7), (5, 6), (6, 6)}
        apple = {(10, 5)}
        if (x, y) in body:
            return "#00FF00"
        if (x, y) in apple:
            return "#FF0000"
        return None
    previews["SNAKE"] = _svg_data_uri(_svg_pixel_grid(snake_icon, bmc.SIGN_WIDTH, bmc.SIGN_HEIGHT))

    # LONGSNAKE: same idea, longer hand-drawn body to visually distinguish it
    # from the regular SNAKE icon at a glance.
    def longsnake_icon(x, y):
        body = {(1, 9), (2, 9), (3, 9), (4, 8), (5, 7), (6, 7), (7, 6), (8, 6),
                (9, 6), (10, 6), (11, 6), (12, 7), (13, 8)}
        apple = {(16, 4)}
        if (x, y) in body:
            return "#00FF00"
        if (x, y) in apple:
            return "#FF0000"
        return None
    previews["LONGSNAKE"] = _svg_data_uri(_svg_pixel_grid(longsnake_icon, bmc.SIGN_WIDTH, bmc.SIGN_HEIGHT))

    # BOUNCE: a small dotted trail suggesting back-and-forth motion, rather
    # than a single dot (which would look identical to "nothing lit").
    def bounce_icon(x, y, mid=bmc.SIGN_HEIGHT // 2):
        if y == mid and x in (4, 14, 24, 34, 44, 54):
            return "#00FF00"
        return None
    previews["BOUNCE"] = _svg_data_uri(_svg_pixel_grid(bounce_icon, bmc.SIGN_WIDTH, bmc.SIGN_HEIGHT))

    return previews


# ---------------------------------------------------------------------------
# Assemble the full page (template + rendered docs + examples JSON) and emit
# it as a PROGMEM C header, same pattern as coolledx_fallback.h: Python
# generates it, arduino-cli compiles it straight into flash, no separate
# upload step, works with no SD card at all.
# ---------------------------------------------------------------------------

def _c_string_literal(text: str) -> str:
    """Encode `text` as one or more adjacent C string literals (C
    concatenates these automatically) so no single line/literal gets
    unreasonably long. Escapes backslashes, quotes, and newlines."""
    escaped = (text.replace("\\", "\\\\")
                    .replace('"', '\\"')
                    .replace("\r", "")
                    .replace("\n", "\\n\n"))
    lines = escaped.split("\n")
    chunks = []
    buf = ""
    for line in lines:
        if len(buf) + len(line) > 400:
            chunks.append(buf)
            buf = ""
        buf += line
    if buf:
        chunks.append(buf)
    return "\n".join(f'  "{c}"' for c in chunks)


def build_index_html() -> str:
    template = open("web_ui_template.html", encoding="utf-8").read()
    docs_html = render_docs_html()
    examples = build_examples()
    previews = build_previews()
    import json
    examples_json = json.dumps(examples)
    previews_json = json.dumps(previews)
    page = (template.replace("__DOCS_HTML__", docs_html)
                     .replace("__EXAMPLES_JSON__", examples_json)
                     .replace("__PREVIEWS_JSON__", previews_json))
    return page


def write_web_ui_header(output_path: str = OUTPUT_HEADER):
    index_html = build_index_html()
    header = []
    header.append("// AUTO-GENERATED by build_web_ui.py -- do not hand-edit.")
    header.append("// Regenerate with: python build_web_ui.py")
    header.append("// Contains the ESP32's on-device web control panel (Control/Raw Send/Docs")
    header.append("// tabs) as one self-contained HTML page (inline CSS+JS, no external")
    header.append("// requests -- the WiFi AP has no internet access). Docs tab is a static")
    header.append("// HTML rendering of PROTOCOL.md baked in at generation time; Raw Send")
    header.append("// examples are real hex from bake_messages_coolledux.py's verified")
    header.append("// *_bytes() functions, never hand-typed.")
    header.append("#pragma once")
    header.append("")
    header.append(f"// {len(index_html)} bytes of HTML/CSS/JS")
    header.append("static const char INDEX_HTML[] PROGMEM =")
    header.append(_c_string_literal(index_html) + ";")
    header.append("")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(header) + "\n")
    print(f"Wrote {output_path} ({len(index_html)} bytes of HTML embedded, "
          f"{sum(1 for _ in open(output_path))} lines total)")


if __name__ == "__main__":
    write_web_ui_header()
